   ###  NumPy Basics: Arrays and Vectorized Computation

 1. NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. 
 
 2. NumPy operations perform complex computations on entire arrays without the need for Python for loops.

In [1]:
import numpy as np

In [ ]:
data = np.random.rand(3, 5)   # rows 3 and columns 5

print(data)

#### Mathematical Operation

In [ ]:
# Multiplication

dataMult = data*10

print(dataMult)

In [ ]:
# Addition

dataAdd = data+data

print(dataAdd)

In [ ]:
# Subtraction

dataAdd = data-data

print(dataAdd)

#### Shape

In [ ]:
print(data.shape)

#### Data Type

In [ ]:
print(data.dtype)

#### Creating ndarrays

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr)
print("Shape : ", arr.shape)          # rows 0 and columns 6

In [ ]:
arrTwo = np.array([[1, 2, 3, 4, 5, 6], [6, 5, 4, 3, 2, 1]])

print(arrTwo)
print("Shape : ", arrTwo.shape)          # rows 2 and columns 6

In [ ]:
print(arrTwo.ndim)        # define dimension of an array

In addition to np.array, there are a number of other functions for creating new arrays. 
These are zeros and ones create arrays of 0s or 1s, respectively, with a given length or shape. 
An empty creates an array without initializing its values to any par‐ticular value. 

In [ ]:
arrZero = np.zeros(10)

arrZero

In [ ]:
arrZerorc = np.zeros((3, 5))

arrZerorc

In [ ]:
arrOne = np.ones(5)

arrOne

In [ ]:
arrOnes = np.ones((3, 5))

arrOnes

In [ ]:
arrZero.dtype

It’s not safe to assume that np.empty will return an array of all zeros. In some cases, it may return uninitialized “garbage” values.

In [ ]:
narray = np.arange(10)
narray

#### Data Types for ndarrays

The data type or dtype is a special object containing the information (or metadata, data about data) the ndarray needs to interpret a chunk of memory as a particular type of data:

In [ ]:
arrFloat = np.array([1, 2, 3, 4], dtype = np.float64)
print(arrFloat)

In [ ]:
arrInt = np.array([1, 2, 3, 4], dtype = np.int)
print(arrInt)

Convert or cast an array from one dtype to another using ndarray’s astype method:

In [ ]:
arr = np.array([1, 2, 3, 4])

arr.dtype

In [9]:
floatArr = arr.astype(np.float64)

print(floatArr)

[2. 2. 3. 4. 5.]


In [2]:
arr = np.array([2.1, 2.6, 3, 4, 5])

arr.dtype

dtype('float64')

In [3]:
arrInt = arr.astype(np.int32)

print(arrInt)

[2 2 3 4 5]


In [10]:
arr = floatArr.view()

In [11]:
arr

array([2., 2., 3., 4., 5.])

In [16]:
arrStr = np.array([2, 3, 4, 5], dtype = np.float)

arrStr

array([2., 3., 4., 5.])

In [18]:
arr = arr.astype(np.int)

In [19]:
arr

array([2, 2, 3, 4, 5])

In [20]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2

array([1, 2, 3, 4, 5])

In [21]:
arr > arr2

array([ True, False, False, False, False])

#### Different method for creating an array

In [22]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [25]:
arr2 = np.arange(2, 15, 3)
arr2

array([ 2,  5,  8, 11, 14])

In [27]:
arr3 = np.arange(2, 8)
arr3

array([2, 3, 4, 5, 6, 7])

In [30]:
arr3[1:3]

array([3, 4])

In [31]:
arr3[:]

array([2, 3, 4, 5, 6, 7])